### PR TITLE
Fix broken setup script & some language errors

### PR DESCRIPTION
**Pull request by dubaaron**
This line was causing setup to fail, because the `configfolder` is being set to a `/Users//.battery` ...
```bash
configfolder=/Users/$calling_usercalling_user/.battery
```

Fixed, and also made some language fixes.

Unfortunately, since the actual setup from brew relies on `curl`ing it from the main repo, this can't be fixed until it's fixed in main.

### CODE REVIEW

**Comment by dubaaron** [comment]
Thanks for making and sharing this important tool.  Hope you will accept my fixes. : )

**Comment by Tokarak** [comment]
BTW a work around is running `battery update` after installing, since that overwrites the config folder.

**Comment by dubaaron** [comment]
> BTW a work around is running `battery update` after installing, since that overwrites the config folder.

Oh, interesting, thank you ...

**Comment by actuallymentor** [comment]
Thank you for your work @dubaaron! Much appreciated!

**Comment by Tokarak** [comment]
Update script is probably broken again after this PR, as battery config folder has been renamed. No?
Users will need to be notified.

**Comment by dubaaron** [comment]
> Update script is probably broken again after this PR, as battery config folder has been renamed. No? Users will need to be notified.

Hmm, I don't think so ... the `$configfolder` was evaluating to 
`/Users//.battery` ... which doesn't work at all; now it just goes to 
`/Users/$calling_user/.battery`, which is what it did before the change that broke it. 

I didn't actually change the path to any folders; I only renamed some variables to correct their spelling, and fixed the accidental breaking of the $calling_user variable

**Pull request merged**
