### PR TITLE
Update magsafe if it's the wrong color

### PR DESCRIPTION
**Pull request by Fizzadar**
Quick fix to update the magsafe color if it's wrong (it seems to reset to orange if you replug it whilst above the threshold).

Closes: #172

### CODE REVIEW

**Comment by ibrado** [comment]
Seems to be the same as my PR #184 ..?

**Comment by actuallymentor** [comment]
Hey @ibrado and @Fizzadar!

Thank you both for catching this, I appreciate that both of you saw an issue and immediately went into "imma fix this" mode.

Given both your PRs (this #201, and #184), which approach do you both feel is the best? Your code uses slightly different approaches and I'd like to merge one of them (and express gratitude to you both).

**Comment by ibrado** [comment]
Hi Mentor (and Fizzador),

Fizzadar's code is more straightforward and appears to handle things
properly, so I have no problem with his PR being merged instead of mine. :-)

I seem to remember working around some odd behavior (some combination of
force-discharging, clamshell, and/or charging while asleep, I think) which
is why I used "AC is attached", but I can't replicate it. If I ever I do,
I'll file a ticket. :-P

Thanks and regards,
Alex

**Comment by bmarkkkkk** [comment]
yes, also having this issue. if it reached it's target, but you unplug, then re-plug... color goes to orange. there are a couple PR's on this.

**Comment by Fizzadar** [comment]
Hi @actuallymentor (& Ibrado) - totally happy with either PR. I _think_ there was a reason I didn't use the other but again I don't recall either, definitely a edge case situation.

**Comment by bmarkkkkk** [comment]
did this get merged?

**Comment by actuallymentor** [comment]
Ended up merging the other one (because I forgot our convo here). Closing this with gratitude to you both!

**Pull request closed without merging**
