### PR TITLE
Use https in network checks

### LINKED ISSUE #151: Incorrect URL for liveness check?
Mentioned in the [README](https://github.com/actuallymentor/battery/blob/main/README.md)
> `icanhasip.com` is used to see if there is an internet connection

and it's implementation here: https://github.com/actuallymentor/battery/blob/79df4af6b7783fd3392ba573938dd739f8b525fd/app/modules/battery.js#L123

May this be changed? 

The URL is not https, and according to https://radar.cloudflare.com/scan/d203c57e-b08e-4831-b278-68419aaf8bac/dom it doesn't seem to show anything of worth.

May this be changed to use [`https://icanhazip.com`](https://icanhazip.com/) instead? Not only is it [now owned by cloudflare](https://major.io/p/a-new-future-for-icanhazip/), but it actually shows [something useful](https://radar.cloudflare.com/scan/8aa43cec-193b-40f7-9699-bf8f201c59ac/dom).

### PR DESCRIPTION
**Pull request by evolutionxbox**
- Move from `icanhasip.com` to `icanhazip.com (Cloudflare)`
- Use https in network checks using the `-k` flag
- Update `README.md`

Resolves #151

### CODE REVIEW

**Comment by actuallymentor** [comment]
Thanks for the PR @evolutionxbox! The https is not too relevant here (since we're just checking if we're online), but I'm not against switching to https.

Why did you disable verification using `-k` though?

**Comment by earthsound** [comment]
If it's getting switched to https, it'd be better to use `-3` since both domains support TLSv1.3. 
`-k` just makes the connection insecure.

**Comment by Tokarak** [comment]
First of all `wget --spider` seems optimised for this task. wget isn't packaged by default on MacOS, so it's probably best to stick to curl.

- `-3` uses SSlv3 (insecure, according to the manage) It's better to use default TLS. There isn't really a good reason for `-k` to be there either.
- `-s` is a minor optimisation.
- I assume the update script cares whether Github works server-side, so `-fL` should be added there.

**Comment by earthsound** [comment]
Yes, meant to say `--tlsv1.3`

**Comment by actuallymentor** [comment]
@Tokarak yes the intent of those calls is just a naive "are we online" check.

Sounds like removing the `-k` is the most important bit, the rest doesn't really matter.

It could even just be a `curl -I` since all I care about is whether we can talk to the url.

@evolutionxbox, could you change the `-k` to -`I` (that's an i, not an L) so I can merge this?

**Comment by actuallymentor** [comment]
@evolutionxbox could you change the `-k` to `-I` so I can merge? I don't mind doing it myself but want you to have the props on your github profile for your contribution :)

**Comment by evolutionxbox** [comment]
@actuallymentor  I didn't mean to ignore the comments. I have updated the PR ✅

**Pull request merged**
